### ISSUE TITLE
IE 10 doesn't work

### ISSUE THREAD

**Issue by quedicesebas** [wstaeblein/ngPercentDisplay#1]

**Comment by wstaeblein** [comment]
Hi there!

It should be working now. There were some vendor prefixes missing in the CSS.

Please let me know if you find any more bugs.

**Comment by quedicesebas** [comment]
Yes, IE 10 is working. IE9 only shows the circle and percentage but not shows the percentage in the circle, and IE8 doesn't works at all

**Comment by wstaeblein** [comment]
I think I was able to make it work on IE9. Have a look. As for IE8, I don't think it is possible.
